version: '3.8'
services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - hadoop-namenode

  hadoop-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-resourcemanager
    ports:
      - "8088:8088"
    networks:
      - hadoop
    depends_on:
      - hadoop-namenode

  hadoop-nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-nodemanager
    networks:
      - hadoop
    depends_on:
      - hadoop-resourcemanager

  hadoop-historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-historyserver
    ports:
      - "8188:8188"
    networks:
      - hadoop
    depends_on:
      - hadoop-namenode
      - hadoop-resourcemanager

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:2.3.2
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
      - HIVE_METASTORE_DB=metastore
      - SERVICE_PRECONDITION="hadoop-namenode:9000"
    ports:
      - "9083:9083"
    networks:
      - hadoop
    depends_on:
      - hadoop-namenode

  hive-server:
    image: bde2020/hive:2.3.2
    container_name: hive-server
    ports:
      - "10000:10000"
    environment:
      - HIVE_EXEC_HADOOP_WORKING_DIR=/tmp
    networks:
      - hadoop
    depends_on:
      - hive-metastore

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hadoop
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
