// 180-Day AI Daily Course Data
// All 180 days with project specs

const DAYS = [
  // MONTH 1: PostgreSQL
  { d: 1, m: 1, title: "Text-to-SQL Generator", concept: "NL to SQL with schema prompting", time: 30, diff: "Easy", tags: ["postgres", "sql", "prompts"] },
  { d: 2, m: 1, title: "Schema Explainer", concept: "Auto-generate plain English docs", time: 30, diff: "Easy", tags: ["postgres", "docs"] },
  { d: 3, m: 1, title: "Query Optimizer", concept: "EXPLAIN ANALYZE + AI suggestions", time: 45, diff: "Medium", tags: ["postgres", "performance"] },
  { d: 4, m: 1, title: "Data Quality Checker", concept: "AI-powered data profiling", time: 45, diff: "Medium", tags: ["postgres", "quality"] },
  { d: 5, m: 1, title: "Auto ER Diagrams", concept: "Generate Mermaid from schema", time: 45, diff: "Medium", tags: ["postgres", "viz"] },
  { d: 6, m: 1, title: "SQL Error Explainer", concept: "Translate errors to plain English", time: 30, diff: "Easy", tags: ["postgres", "errors"] },
  { d: 7, m: 1, title: "NL SQL SaaS v0.1", concept: "WEEKEND — Deploy MVP", time: 180, diff: "Medium", tags: ["weekend", "deploy"], weekend: true },
  { d: 8, m: 1, title: "Migration Generator", concept: "Auto-generate UP/DOWN migrations", time: 45, diff: "Medium", tags: ["postgres", "schema"] },
  { d: 9, m: 1, title: "Row-Level Explanations", concept: "Explain any row in plain English", time: 30, diff: "Easy", tags: ["postgres", "explain"] },
  { d: 10, m: 1, title: "SQL Anomaly Detector", concept: "Find unusual patterns in time-series", time: 60, diff: "Hard", tags: ["postgres", "anomaly"] },
  { d: 11, m: 1, title: "Natural Language Dashboard", concept: "Question → chart with Streamlit", time: 60, diff: "Medium", tags: ["postgres", "viz", "ui"] },
  { d: 12, m: 1, title: "SQL to Pandas", concept: "Translate SQL to pandas code", time: 30, diff: "Easy", tags: ["postgres", "pandas"] },
  { d: 13, m: 1, title: "Test Data Generator", concept: "Realistic synthetic data from schema", time: 45, diff: "Medium", tags: ["postgres", "synthetic"] },
  { d: 14, m: 1, title: "Auth + Deploy", concept: "WEEKEND — Production deploy with auth", time: 180, diff: "Medium", tags: ["weekend", "deploy"], weekend: true },
  { d: 15, m: 1, title: "Embeddings from Text", concept: "Generate + store embeddings in pgvector", time: 45, diff: "Medium", tags: ["postgres", "embeddings"] },
  { d: 16, m: 1, title: "Semantic Search over Rows", concept: "Find similar rows by meaning", time: 45, diff: "Medium", tags: ["postgres", "search", "vectors"] },
  { d: 17, m: 1, title: "RAG over Schema", concept: "Chatbot that answers schema questions", time: 60, diff: "Medium", tags: ["postgres", "rag"] },
  { d: 18, m: 1, title: "Hybrid Search", concept: "Combine keyword (BM25) + vector search", time: 60, diff: "Hard", tags: ["postgres", "hybrid"] },
  { d: 19, m: 1, title: "Auto-Embed on Insert", concept: "Background worker for embedding queue", time: 45, diff: "Medium", tags: ["postgres", "automation"] },
  { d: 20, m: 1, title: "Vector Search UI", concept: "Streamlit search interface", time: 60, diff: "Medium", tags: ["postgres", "ui", "search"] },
  { d: 21, m: 1, title: "Polish + Share", concept: "WEEKEND — Deploy + blog post", time: 180, diff: "Medium", tags: ["weekend", "share"], weekend: true },
  { d: 22, m: 1, title: "Multi-Table RAG", concept: "Cross-table question answering", time: 60, diff: "Hard", tags: ["postgres", "rag", "multi"] },
  { d: 23, m: 1, title: "Result Summarizer", concept: "Auto-summarize query results", time: 30, diff: "Easy", tags: ["postgres", "summary"] },
  { d: 24, m: 1, title: "CSV to SQL Loader", concept: "Upload CSV → table → SQL", time: 45, diff: "Medium", tags: ["postgres", "etl"] },
  { d: 25, m: 1, title: "pgvector Index Tuner", concept: "Benchmark HNSW vs IVFFlat", time: 60, diff: "Hard", tags: ["postgres", "performance"] },
  { d: 26, m: 1, title: "Embedding Drift Detector", concept: "Statistical test for distribution shift", time: 60, diff: "Hard", tags: ["postgres", "monitoring"] },
  { d: 27, m: 1, title: "RAG with Citations", concept: "Answers that cite source rows", time: 60, diff: "Medium", tags: ["postgres", "rag", "citations"] },
  { d: 28, m: 1, title: "RAG Evaluation Harness", concept: "WEEKEND — Build RAGAS-style tests", time: 180, diff: "Hard", tags: ["weekend", "eval"], weekend: true },
  { d: 29, m: 1, title: "Multi-Language SQL", concept: "Question in any language → SQL", time: 45, diff: "Easy", tags: ["postgres", "i18n"] },
  { d: 30, m: 1, title: "MONTH 1 CAPSTONE", concept: "NL SQL Assistant v1 — full product", time: 360, diff: "Hard", tags: ["capstone"], capstone: true },

  // MONTH 2: REST APIs
  { d: 31, m: 2, title: "Weather API Agent", concept: "Function calling for OpenWeather", time: 30, diff: "Easy", tags: ["api", "tools"] },
  { d: 32, m: 2, title: "GitHub PR Summarizer", concept: "Fetch + summarize PRs", time: 45, diff: "Easy", tags: ["api", "github"] },
  { d: 33, m: 2, title: "Slack Message Router", concept: "Classify + route messages", time: 45, diff: "Medium", tags: ["api", "slack"] },
  { d: 34, m: 2, title: "Stripe Analytics", concept: "Natural language revenue queries", time: 45, diff: "Medium", tags: ["api", "stripe"] },
  { d: 35, m: 2, title: "Notion Q&A", concept: "Ask questions about your Notion pages", time: 60, diff: "Medium", tags: ["api", "notion"] },
  { d: 36, m: 2, title: "Linear Triage", concept: "Auto-categorize + prioritize issues", time: 60, diff: "Medium", tags: ["api", "linear"] },
  { d: 37, m: 2, title: "Multi-API Dashboard", concept: "WEEKEND — Combine 5+ APIs", time: 180, diff: "Hard", tags: ["weekend", "ui"], weekend: true },
  { d: 38, m: 2, title: "Async API Client", concept: "httpx + asyncio", time: 30, diff: "Easy", tags: ["api", "async"] },
  { d: 39, m: 2, title: "Parallel API Calls", concept: "asyncio.gather for speed", time: 45, diff: "Medium", tags: ["api", "async"] },
  { d: 40, m: 2, title: "Retry with Backoff", concept: "Resilient API calls", time: 30, diff: "Easy", tags: ["api", "errors"] },
  { d: 41, m: 2, title: "Rate Limit Handler", concept: "Token bucket, exponential backoff", time: 45, diff: "Medium", tags: ["api", "limits"] },
  { d: 42, m: 2, title: "Response Caching", concept: "Redis + semantic keys", time: 60, diff: "Medium", tags: ["api", "cache", "redis"] },
  { d: 43, m: 2, title: "Circuit Breaker", concept: "Stop calling failing APIs", time: 45, diff: "Medium", tags: ["api", "resilience"] },
  { d: 44, m: 2, title: "Resilient Wrapper Library", concept: "WEEKEND — Production-grade client", time: 180, diff: "Hard", tags: ["weekend", "lib"], weekend: true },
  { d: 45, m: 2, title: "Webhook Receiver", concept: "FastAPI endpoint to receive webhooks", time: 45, diff: "Easy", tags: ["api", "webhook"] },
  { d: 46, m: 2, title: "Stripe → AI Categorization", concept: "Auto-tag incoming payments", time: 60, diff: "Medium", tags: ["api", "webhook", "stripe"] },
  { d: 47, m: 2, title: "GitHub → AI Code Review", concept: "Auto-review on PR open", time: 60, diff: "Medium", tags: ["api", "webhook", "github"] },
  { d: 48, m: 2, title: "Slack → AI Moderation", concept: "Flag inappropriate messages", time: 60, diff: "Medium", tags: ["api", "webhook", "slack"] },
  { d: 49, m: 2, title: "ngrok Local Webhooks", concept: "Test webhooks in dev", time: 30, diff: "Easy", tags: ["api", "dev"] },
  { d: 50, m: 2, title: "Webhook Signature Verify", concept: "HMAC + replay protection", time: 45, diff: "Medium", tags: ["api", "security"] },
  { d: 51, m: 2, title: "Event-Driven System", concept: "WEEKEND — Full event pipeline", time: 180, diff: "Hard", tags: ["weekend", "events"], weekend: true },
  { d: 52, m: 2, title: "OAuth 2.0 Flow", concept: "GitHub OAuth in FastAPI", time: 60, diff: "Medium", tags: ["api", "oauth"] },
  { d: 53, m: 2, title: "Token Refresh", concept: "Auto-refresh expired tokens", time: 45, diff: "Medium", tags: ["api", "oauth"] },
  { d: 54, m: 2, title: "Per-User Credentials", concept: "Multi-tenant token storage", time: 60, diff: "Medium", tags: ["api", "multi-tenant"] },
  { d: 55, m: 2, title: "Multi-Tenant Quotas", concept: "Per-user API rate limits", time: 60, diff: "Hard", tags: ["api", "quotas"] },
  { d: 56, m: 2, title: "Audit Log", concept: "Log every API call with cost", time: 45, diff: "Easy", tags: ["api", "audit"] },
  { d: 57, m: 2, title: "Anomaly Detection", concept: "Unusual API usage alerts", time: 60, diff: "Hard", tags: ["api", "security"] },
  { d: 58, m: 2, title: "OAuth Dashboard", concept: "WEEKEND — User-facing OAuth UI", time: 180, diff: "Hard", tags: ["weekend", "ui"], weekend: true },
  { d: 59, m: 2, title: "Polish + Tests", concept: "Test coverage + refactor", time: 90, diff: "Medium", tags: ["test"] },
  { d: 60, m: 2, title: "MONTH 2 CAPSTONE", concept: "Ops Agent — manage SaaS via AI", time: 360, diff: "Hard", tags: ["capstone"], capstone: true },

  // MONTH 3: Documents & Search
  { d: 61, m: 3, title: "PDF Text Extraction", concept: "pypdf for clean text", time: 30, diff: "Easy", tags: ["docs", "pdf"] },
  { d: 62, m: 3, title: "Word/Excel/PPT Parsing", concept: "unstructured library", time: 45, diff: "Medium", tags: ["docs", "office"] },
  { d: 63, m: 3, title: "OCR for Scanned PDFs", concept: "Tesseract + preprocessing", time: 60, diff: "Medium", tags: ["docs", "ocr"] },
  { d: 64, m: 3, title: "Web Scraper + Chunker", concept: "Crawl + split into chunks", time: 60, diff: "Medium", tags: ["docs", "scraping"] },
  { d: 65, m: 3, title: "Sitemap Crawler", concept: "Recursive crawler with dedup", time: 60, diff: "Medium", tags: ["docs", "crawling"] },
  { d: 66, m: 3, title: "Notion/Confluence Export", concept: "API-based bulk export", time: 60, diff: "Medium", tags: ["docs", "api"] },
  { d: 67, m: 3, title: "Doc Ingestion Pipeline", concept: "WEEKEND — End-to-end ETL", time: 180, diff: "Hard", tags: ["weekend", "etl"], weekend: true },
  { d: 68, m: 3, title: "Index in Elasticsearch", concept: "Bulk indexing with mappings", time: 60, diff: "Medium", tags: ["search", "elasticsearch"] },
  { d: 69, m: 3, title: "BM25 Search", concept: "Full-text search basics", time: 45, diff: "Easy", tags: ["search"] },
  { d: 70, m: 3, title: "Multi-Field Search", concept: "Title + body + tags boost", time: 45, diff: "Medium", tags: ["search"] },
  { d: 71, m: 3, title: "Faceted Search", concept: "Filters + aggregations", time: 60, diff: "Medium", tags: ["search", "ui"] },
  { d: 72, m: 3, title: "Highlighting", concept: "Show matched terms in context", time: 30, diff: "Easy", tags: ["search", "ui"] },
  { d: 73, m: 3, title: "Search Autocomplete", concept: "Suggest-as-you-type", time: 45, diff: "Medium", tags: ["search", "ui"] },
  { d: 74, m: 3, title: "Search UI", concept: "WEEKEND — Faceted search frontend", time: 180, diff: "Medium", tags: ["weekend", "ui"], weekend: true },
  { d: 75, m: 3, title: "Embed All Docs", concept: "Generate + store vectors", time: 60, diff: "Medium", tags: ["search", "embeddings"] },
  { d: 76, m: 3, title: "Vector Search in ES", concept: "dense_vector field", time: 60, diff: "Medium", tags: ["search", "vectors"] },
  { d: 77, m: 3, title: "Hybrid BM25 + Vector", concept: "RRF (reciprocal rank fusion)", time: 60, diff: "Hard", tags: ["search", "hybrid"] },
  { d: 78, m: 3, title: "Re-ranking (Cohere)", concept: "Second-stage precision boost", time: 60, diff: "Hard", tags: ["search", "rerank"] },
  { d: 79, m: 3, title: "Query Understanding", concept: "Spell fix + expansion", time: 60, diff: "Medium", tags: ["search", "nlp"] },
  { d: 80, m: 3, title: "Personalized Ranking", concept: "User history boost", time: 90, diff: "Hard", tags: ["search", "personalization"] },
  { d: 81, m: 3, title: "Search Quality Eval", concept: "WEEKEND — nDCG, MRR, CTR", time: 180, diff: "Hard", tags: ["weekend", "eval"], weekend: true },
  { d: 82, m: 3, title: "RAG with Citations", concept: "Answer + paragraph refs", time: 60, diff: "Medium", tags: ["rag", "citations"] },
  { d: 83, m: 3, title: "Conversational RAG", concept: "Multi-turn with history", time: 60, diff: "Hard", tags: ["rag", "chat"] },
  { d: 84, m: 3, title: "Multi-Hop RAG", concept: "Follow-up questions", time: 90, diff: "Hard", tags: ["rag"] },
  { d: 85, m: 3, title: "Streaming RAG", concept: "Token-by-token responses", time: 60, diff: "Medium", tags: ["rag", "streaming"] },
  { d: 86, m: 3, title: "RAG Evaluation", concept: "RAGAS framework", time: 60, diff: "Medium", tags: ["rag", "eval"] },
  { d: 87, m: 3, title: "RAG Observability", concept: "LangSmith traces", time: 60, diff: "Medium", tags: ["rag", "monitoring"] },
  { d: 88, m: 3, title: "RAG Cost Optimization", concept: "WEEKEND — Cut costs 50%", time: 180, diff: "Hard", tags: ["weekend", "cost"], weekend: true },
  { d: 89, m: 3, title: "Load Test", concept: "10K docs, 100 QPS", time: 90, diff: "Hard", tags: ["performance"] },
  { d: 90, m: 3, title: "MONTH 3 CAPSTONE", concept: "Support AI — answer 10K tickets", time: 360, diff: "Hard", tags: ["capstone"], capstone: true },

  // MONTH 4: Files & Media
  { d: 91, m: 4, title: "S3 Presigned URLs", concept: "Client-side direct upload", time: 45, diff: "Easy", tags: ["s3", "upload"] },
  { d: 92, m: 4, title: "Multi-Part Upload", concept: "Large files reliably", time: 60, diff: "Medium", tags: ["s3", "upload"] },
  { d: 93, m: 4, title: "Image Processing", concept: "Resize, compress, thumbnails", time: 60, diff: "Medium", tags: ["images", "pipeline"] },
  { d: 94, m: 4, title: "Virus Scanning", concept: "ClamAV integration", time: 60, diff: "Medium", tags: ["security"] },
  { d: 95, m: 4, title: "CDN Integration", concept: "CloudFront/R2 caching", time: 60, diff: "Medium", tags: ["cdn"] },
  { d: 96, m: 4, title: "File Metadata + Tags", concept: "Auto-tagging with AI", time: 60, diff: "Medium", tags: ["metadata"] },
  { d: 97, m: 4, title: "File Upload Service", concept: "WEEKEND — Full upload pipeline", time: 180, diff: "Hard", tags: ["weekend", "service"], weekend: true },
  { d: 98, m: 4, title: "DALL-E 3 Generation", concept: "Image from text prompt", time: 30, diff: "Easy", tags: ["images", "gen"] },
  { d: 99, m: 4, title: "Stable Diffusion", concept: "Local open-source generation", time: 90, diff: "Hard", tags: ["images", "gen"] },
  { d: 100, m: 4, title: "GPT-4V Understanding", concept: "Image → text descriptions", time: 45, diff: "Easy", tags: ["images", "vlm"] },
  { d: 101, m: 4, title: "Image Similarity (CLIP)", concept: "Find similar images", time: 60, diff: "Medium", tags: ["images", "search"] },
  { d: 102, m: 4, title: "Image Captioning", concept: "Auto-generate alt text", time: 45, diff: "Easy", tags: ["images", "gen"] },
  { d: 103, m: 4, title: "Object Detection (YOLO)", concept: "Detect + label objects", time: 90, diff: "Hard", tags: ["images", "detection"] },
  { d: 104, m: 4, title: "Visual Search App", concept: "WEEKEND — Search by image", time: 180, diff: "Hard", tags: ["weekend", "ui"], weekend: true },
  { d: 105, m: 4, title: "Whisper Transcription", concept: "Audio → text", time: 30, diff: "Easy", tags: ["audio"] },
  { d: 106, m: 4, title: "Speaker Diarization", concept: "Who spoke when", time: 60, diff: "Hard", tags: ["audio"] },
  { d: 107, m: 4, title: "Real-Time Transcription", concept: "Streaming audio → text", time: 90, diff: "Hard", tags: ["audio", "streaming"] },
  { d: 108, m: 4, title: "Audio Embeddings", concept: "Similarity search for sounds", time: 60, diff: "Medium", tags: ["audio", "search"] },
  { d: 109, m: 4, title: "Text-to-Speech", concept: "ElevenLabs, OpenAI TTS", time: 45, diff: "Easy", tags: ["audio", "gen"] },
  { d: 110, m: 4, title: "Voice Cloning (ethical)", concept: "Clone with consent", time: 90, diff: "Hard", tags: ["audio", "gen"] },
  { d: 111, m: 4, title: "Podcast Search Engine", concept: "WEEKEND — Search inside podcasts", time: 180, diff: "Hard", tags: ["weekend", "search"], weekend: true },
  { d: 112, m: 4, title: "Video Frame Extract", concept: "Sample frames from video", time: 60, diff: "Medium", tags: ["video"] },
  { d: 113, m: 4, title: "Scene Detection", concept: "Auto-detect scene changes", time: 90, diff: "Hard", tags: ["video"] },
  { d: 114, m: 4, title: "Video Summarization", concept: "Auto-highlight reel", time: 90, diff: "Hard", tags: ["video", "summary"] },
  { d: 115, m: 4, title: "PDF Table Extraction", concept: "Tables → CSV/Excel", time: 60, diff: "Medium", tags: ["pdf", "etl"] },
  { d: 116, m: 4, title: "Figure/Chart Extraction", concept: "Extract images from PDFs", time: 60, diff: "Medium", tags: ["pdf", "images"] },
  { d: 117, m: 4, title: "Form Parsing", concept: "PDF forms → JSON", time: 90, diff: "Hard", tags: ["pdf", "etl"] },
  { d: 118, m: 4, title: "Doc Automation", concept: "WEEKEND — End-to-end PDF pipeline", time: 180, diff: "Hard", tags: ["weekend", "automation"], weekend: true },
  { d: 119, m: 4, title: "Cost Analysis", concept: "Per-file cost breakdown", time: 60, diff: "Medium", tags: ["cost"] },
  { d: 120, m: 4, title: "MONTH 4 CAPSTONE", concept: "Media Pipeline — upload → transcribe → index", time: 360, diff: "Hard", tags: ["capstone"], capstone: true },

  // MONTH 5: Real-Time Streams
  { d: 121, m: 5, title: "Redis Streams Pub/Sub", concept: "Basic pub/sub pattern", time: 45, diff: "Easy", tags: ["streams", "redis"] },
  { d: 122, m: 5, title: "Producer/Consumer", concept: "Work queue with workers", time: 60, diff: "Medium", tags: ["streams"] },
  { d: 123, m: 5, title: "Worker Pool", concept: "Concurrent consumers", time: 60, diff: "Medium", tags: ["streams", "concurrency"] },
  { d: 124, m: 5, title: "Dead-Letter Queue", concept: "Handle poison messages", time: 60, diff: "Medium", tags: ["streams", "errors"] },
  { d: 125, m: 5, title: "Idempotency Keys", concept: "Process messages exactly once", time: 60, diff: "Hard", tags: ["streams", "reliability"] },
  { d: 126, m: 5, title: "Priority Queues", concept: "Process high-priority first", time: 60, diff: "Medium", tags: ["streams"] },
  { d: 127, m: 5, title: "Async Job System", concept: "WEEKEND — Production job system", time: 180, diff: "Hard", tags: ["weekend", "jobs"], weekend: true },
  { d: 128, m: 5, title: "Kafka Producer", concept: "Redpanda + kafka-python", time: 60, diff: "Medium", tags: ["kafka"] },
  { d: 129, m: 5, title: "Kafka Consumer", concept: "Offset management", time: 60, diff: "Medium", tags: ["kafka"] },
  { d: 130, m: 5, title: "Topic Partitioning", concept: "Scale with partitions", time: 60, diff: "Hard", tags: ["kafka"] },
  { d: 131, m: 5, title: "Consumer Groups", concept: "Multiple consumers, one topic", time: 60, diff: "Hard", tags: ["kafka"] },
  { d: 132, m: 5, title: "Schema Registry", concept: "Avro/JSON schemas", time: 90, diff: "Hard", tags: ["kafka", "schemas"] },
  { d: 133, m: 5, title: "Stream Processing", concept: "Windowed aggregations", time: 90, diff: "Hard", tags: ["kafka", "processing"] },
  { d: 134, m: 5, title: "Real-Time Log Pipeline", concept: "WEEKEND — Logs → Kafka → ES", time: 180, diff: "Hard", tags: ["weekend", "logs"], weekend: true },
  { d: 135, m: 5, title: "Event → AI → Action", concept: "AI in the loop", time: 60, diff: "Medium", tags: ["events", "ai"] },
  { d: 136, m: 5, title: "Stream Enrichment", concept: "LLM enriches events", time: 60, diff: "Medium", tags: ["events", "llm"] },
  { d: 137, m: 5, title: "Content Moderation", concept: "Real-time flag/remove", time: 90, diff: "Hard", tags: ["events", "moderation"] },
  { d: 138, m: 5, title: "Live Chat Assistant", concept: "WebSocket + AI", time: 90, diff: "Hard", tags: ["events", "chat"] },
  { d: 139, m: 5, title: "Real-Time Translation", concept: "Stream → translate → emit", time: 90, diff: "Hard", tags: ["events", "translate"] },
  { d: 140, m: 5, title: "Anomaly Detection", concept: "Stream → detect → alert", time: 90, diff: "Hard", tags: ["events", "anomaly"] },
  { d: 141, m: 5, title: "Real-Time AI Dashboard", concept: "WEEKEND — Live metrics + AI", time: 180, diff: "Hard", tags: ["weekend", "dashboard"], weekend: true },
  { d: 142, m: 5, title: "OpenTelemetry Tracing", concept: "Distributed tracing", time: 60, diff: "Medium", tags: ["observability"] },
  { d: 143, m: 5, title: "Metrics: QPS, Latency", concept: "Prometheus-style metrics", time: 60, diff: "Medium", tags: ["observability", "metrics"] },
  { d: 144, m: 5, title: "Cost Attribution", concept: "Per-tenant cost tracking", time: 60, diff: "Medium", tags: ["cost"] },
  { d: 145, m: 5, title: "Auto-Scaling Workers", concept: "K8s HPA based on queue depth", time: 90, diff: "Hard", tags: ["scaling"] },
  { d: 146, m: 5, title: "Backpressure", concept: "Don't overwhelm downstream", time: 60, diff: "Hard", tags: ["streams", "reliability"] },
  { d: 147, m: 5, title: "Multi-Region", concept: "Replicate across regions", time: 90, diff: "Hard", tags: ["scaling", "geo"] },
  { d: 148, m: 5, title: "Production Stream App", concept: "WEEKEND — Hardened system", time: 180, diff: "Hard", tags: ["weekend", "production"], weekend: true },
  { d: 149, m: 5, title: "Load + Chaos Test", concept: "Break it on purpose", time: 90, diff: "Hard", tags: ["testing"] },
  { d: 150, m: 5, title: "MONTH 5 CAPSTONE", concept: "AI Incident Response for SREs", time: 360, diff: "Hard", tags: ["capstone"], capstone: true },

  // MONTH 6: Vector Search
  { d: 151, m: 6, title: "Pinecone Basics", concept: "Insert, search, delete", time: 45, diff: "Easy", tags: ["vectors", "pinecone"] },
  { d: 152, m: 6, title: "Weaviate Schema", concept: "Class design + properties", time: 60, diff: "Medium", tags: ["vectors", "weaviate"] },
  { d: 153, m: 6, title: "Qdrant Payloads", concept: "Filter on metadata", time: 60, diff: "Medium", tags: ["vectors", "qdrant"] },
  { d: 154, m: 6, title: "Chroma Local Dev", concept: "Vector DB for prototyping", time: 45, diff: "Easy", tags: ["vectors", "chroma"] },
  { d: 155, m: 6, title: "Embedding Model Compare", concept: "OpenAI vs Cohere vs Voyage", time: 60, diff: "Medium", tags: ["vectors", "embeddings"] },
  { d: 156, m: 6, title: "Index Types", concept: "HNSW vs IVFFlat vs ScaNN", time: 60, diff: "Hard", tags: ["vectors", "performance"] },
  { d: 157, m: 6, title: "Multi-DB Benchmark", concept: "WEEKEND — Compare all 4 vector DBs", time: 180, diff: "Hard", tags: ["weekend", "benchmark"], weekend: true },
  { d: 158, m: 6, title: "Metadata Filtering", concept: "Pre-filter before vector search", time: 45, diff: "Medium", tags: ["vectors", "filter"] },
  { d: 159, m: 6, title: "Hybrid Search", concept: "Vector + keyword fusion", time: 60, diff: "Hard", tags: ["vectors", "hybrid"] },
  { d: 160, m: 6, title: "Cross-Encoder Re-rank", concept: "Boost precision", time: 60, diff: "Hard", tags: ["vectors", "rerank"] },
  { d: 161, m: 6, title: "Multi-Vector Search", concept: "ColBERT-style per-token", time: 90, diff: "Hard", tags: ["vectors", "colbert"] },
  { d: 162, m: 6, title: "Sparse + Dense (SPLADE)", concept: "Best of both worlds", time: 90, diff: "Hard", tags: ["vectors", "sparse"] },
  { d: 163, m: 6, title: "Late Interaction", concept: "ColBERT v2 implementation", time: 90, diff: "Hard", tags: ["vectors", "colbert"] },
  { d: 164, m: 6, title: "Search Quality Benchmark", concept: "WEEKEND — Measure nDCG@10", time: 180, diff: "Hard", tags: ["weekend", "eval"], weekend: true },
  { d: 165, m: 6, title: "Sharding Strategies", concept: "Hash, range, custom", time: 60, diff: "Hard", tags: ["vectors", "scaling"] },
  { d: 166, m: 6, title: "Read Replicas", concept: "Scale reads horizontally", time: 60, diff: "Medium", tags: ["vectors", "scaling"] },
  { d: 167, m: 6, title: "Backup + Restore", concept: "Snapshot, restore, verify", time: 60, diff: "Medium", tags: ["vectors", "ops"] },
  { d: 168, m: 6, title: "Cost Optimization", concept: "Right-size your deployment", time: 60, diff: "Medium", tags: ["vectors", "cost"] },
  { d: 169, m: 6, title: "Multi-Tenancy", concept: "Namespaces per tenant", time: 60, diff: "Hard", tags: ["vectors", "multi-tenant"] },
  { d: 170, m: 6, title: "Vector DB Monitoring", concept: "Latency, recall, cost", time: 60, diff: "Medium", tags: ["vectors", "observability"] },
  { d: 171, m: 6, title: "Production Search Service", concept: "WEEKEND — Hardened + monitored", time: 180, diff: "Hard", tags: ["weekend", "production"], weekend: true },
  { d: 172, m: 6, title: "Multi-Modal (CLIP)", concept: "Image + text in same space", time: 90, diff: "Hard", tags: ["vectors", "multimodal"] },
  { d: 173, m: 6, title: "Image + Text Search", concept: "Search by either modality", time: 90, diff: "Hard", tags: ["vectors", "multimodal"] },
  { d: 174, m: 6, title: "Cross-Lingual Search", concept: "Query in any language", time: 90, diff: "Hard", tags: ["vectors", "i18n"] },
  { d: 175, m: 6, title: "Personalized Ranking", concept: "Boost based on user history", time: 90, diff: "Hard", tags: ["vectors", "personalization"] },
  { d: 176, m: 6, title: "A/B Test Search", concept: "Measure quality changes", time: 90, diff: "Hard", tags: ["vectors", "ab-test"] },
  { d: 177, m: 6, title: "Capstone MVP", concept: "Build your AI SaaS", time: 360, diff: "Hard", tags: ["capstone", "mvp"] },
  { d: 178, m: 6, title: "Capstone Polish", concept: "WEEKEND — UI/UX + deploy", time: 360, diff: "Hard", tags: ["weekend", "capstone"], weekend: true },
  { d: 179, m: 6, title: "Demo Video + Post", concept: "Loom + launch blog", time: 180, diff: "Medium", tags: ["marketing"] },
  { d: 180, m: 6, title: "🚀 CAPSTONE LAUNCH", concept: "Live demo + 10 paying users", time: 360, diff: "Hard", tags: ["capstone", "launch"], capstone: true },
];

const MONTH_INFO = {
  1: { name: "PostgreSQL", color: "#0071E3", icon: "🗄️" },
  2: { name: "REST APIs", color: "#34C759", icon: "🌐" },
  3: { name: "Documents & Search", color: "#FF9500", icon: "📚" },
  4: { name: "Files & Media", color: "#AF52DE", icon: "📁" },
  5: { name: "Real-Time Streams", color: "#FF2D55", icon: "⚡" },
  6: { name: "Vector Search", color: "#FFD60A", icon: "🎯" }
};
