"""Setup script for the system_design course.

Lets you `import code.service` from anywhere by installing the course
in editable mode.

    pip install -e system_design
"""

from setuptools import setup, find_packages

setup(
    name="system-design-course",
    version="1.0.0",
    description="A complete, runnable System Design course with 71 lessons across 11 modules.",
    author="Prem Vishnoi",
    author_email="pvishnoi@avilx.com",
    url="https://medium.com/@premvishnoi",
    packages=find_packages(
        include=[
            "common",
            "00_overview.code",
            "00_overview.tests",
            "01_url_shortener.code",
            "01_url_shortener.tests",
            "02_typeahead.code",
            "02_typeahead.tests",
            "03_instagram.code",
            "03_instagram.tests",
            "04_twitter.code",
            "04_twitter.tests",
            "05_newsfeed.code",
            "05_newsfeed.tests",
            "06_yt_or_netflix.code",
            "06_yt_or_netflix.tests",
            "07_message_queue.code",
            "07_message_queue.tests",
            "08_webhook_delivery.code",
            "08_webhook_delivery.tests",
            "09_uber_eats.code",
            "09_uber_eats.tests",
            "10_web_crawler.code",
            "10_web_crawler.tests",
            "11_job_scheduler.code",
            "11_job_scheduler.tests",
            "12_user_data_export.code",
            "12_user_data_export.tests",
            "13_kv_store.code",
            "13_kv_store.tests",
            "14_rate_limiter.code",
            "14_rate_limiter.tests",
            "15_distributed_lru.code",
            "15_distributed_lru.tests",
            "16_dropbox.code",
            "16_dropbox.tests",
            "17_s3_storage.code",
            "17_s3_storage.tests",
            "18_ticketmaster.code",
            "18_ticketmaster.tests",
            "19_hotel_booking.code",
            "19_hotel_booking.tests",
            "20_parking_garage.code",
            "20_parking_garage.tests",
            "21_metrics_logging.code",
            "21_metrics_logging.tests",
            "22_apm.code",
            "22_apm.tests",
            "23_doc_processing.code",
            "23_doc_processing.tests",
            "24_zillow.code",
            "24_zillow.tests",
            "25_weather_app.code",
            "25_weather_app.tests",
            "26_messenger.code",
            "26_messenger.tests",
            "27_whatsapp.code",
            "27_whatsapp.tests",
            "28_chess.code",
            "28_chess.tests",
            "29_slack.code",
            "29_slack.tests",
            "30_google_docs.code",
            "30_google_docs.tests",
            "31_tiktok.code",
            "31_tiktok.tests",
            "32_twitch.code",
            "32_twitch.tests",
            "33_ai_support.code",
            "33_ai_support.tests",
            "34_chatgpt.code",
            "34_chatgpt.tests",
            "35_file_uploader.code",
            "35_file_uploader.tests",
            "36_llm_batching.code",
            "36_llm_batching.tests",
            "37_claude_code.code",
            "37_claude_code.tests",
            "38_voice_ai.code",
            "38_voice_ai.tests",
            "39_reddit_homepage.code",
            "39_reddit_homepage.tests",
        ],
    ),
    python_requires=">=3.10",
    install_requires=[
        "flask>=3.0",
        "requests>=2.31",
        "pytest>=8.0",
        "numpy>=1.24",
        "pandas>=2.0",
    ],
)
