from .models import Document

DOCUMENTS = [
    Document("policy-001", "Makro Promotion Approval Policy", "Promotions above 20 percent discount require category manager approval. Promotions above 30 percent require commercial director approval.", "sharepoint", "sharepoint://promotion-policy", {"type": "policy", "updated": "2026-07-15"}, ["commercial", "analytics"]),
    Document("tech-001", "Enterprise Search Quality Playbook", "Evaluate retrieval separately from answer quality. Retrieval metrics include recall at k, precision at k, mean reciprocal rank and normalized discounted cumulative gain. Answer metrics include correctness, relevance, faithfulness and citation coverage.", "confluence", "confluence://search-quality", {"type": "guide", "updated": "2026-08-10"}, ["analytics"]),
    Document("tech-002", "Context Management Standard", "Reduce context bloat with metadata filters, deduplication, reranking, top k selection and context budgeting. Pass only relevant evidence to the language model.", "confluence", "confluence://context-management", {"type": "standard", "updated": "2026-08-12"}, ["analytics"]),
    Document("tech-003", "Agent Recovery Standard", "Retry repeats a failed operation for transient errors such as timeouts. Resume continues an interrupted workflow from a durable checkpoint without repeating completed side effects.", "confluence", "confluence://agent-recovery", {"type": "standard", "updated": "2026-08-13"}, ["analytics"]),
    Document("tech-004", "MCP Tool Integration Guide", "A tool contract separates agent reasoning from implementation. Typed schemas validate tool arguments while adapters hide authentication, transport and legacy response formats.", "confluence", "confluence://mcp-tools", {"type": "guide", "updated": "2026-08-14"}, ["analytics", "technology"]),
    Document("arch-001", "Indexing and Federated Connector Architecture", "Indexed search provides low latency ranking over synchronized content. Federated connectors query authoritative systems at request time for fresh operational data.", "jira", "jira://index-federation", {"type": "architecture", "updated": "2026-08-15"}, ["analytics", "technology"]),
    Document("product-001", "Bulk Cooking Oil Product Guide", "Bulk cooking oil includes palm, soybean, sunflower and deep frying oil in five and ten litre packs for restaurant customers.", "catalog", "catalog://cooking-oil", {"type": "product", "updated": "2026-08-01"}, ["all"]),
]
